extensions = ['sphinx.ext.mathjax']
source_suffix = '.rst'
master_doc = 'index'
project = 'tttnns-blog'
copyright = '2017, TitanSnow'
author = 'TitanSnow'
language = 'zh_CN'
exclude_patterns = ['_build']
html_theme_path = ['.']
html_theme = 'diktat'
